### PR TITLE
Patch Readme

### PR DESCRIPTION
**Pull request by khorsmann**
The example sql creates an admin user with wrong sql settings. Without first_name and last_name you cannot update the password correct.

### CODE REVIEW

**Comment by bogdan-iancu** [comment]
Thank you @khorsmann - could you detail on the error you found while updating an user without First and Last name ?

**Comment by khorsmann** [comment]
Okay - i try to described it by the database results.

I insert this admin like the readme described it:
`
INSERT INTO ocp_admin_privileges (username,password,ha1,available_tools,permissions) values ('admintest','admin',md5('admintest:admin'),'all','all');
`


SELECT the result:
`
MariaDB [opensips]> select username,password,first_name,last_name,ha1,available_tools,permissions from ocp_admin_privileges where id=57;
+-----------+----------+------------+-----------+----------------------------------+-----------------+-------------+
| username  | password | first_name | last_name | ha1                              | available_tools | permissions |
+-----------+----------+------------+-----------+----------------------------------+-----------------+-------------+
| admintest | admin    |            |           | 0f8b2e317400eb6bbc94b2ac15b5ab34 | all             | all         |
+-----------+----------+------------+-----------+----------------------------------+-----------------+-------------+
1 row in set (0.00 sec)
`

Via the webinterface i change the password - webinterface didnt change it as you see in the Select before and after password change:

`
MariaDB [opensips]> select username,password,first_name,last_name,ha1,available_tools,permissions from ocp_admin_privileges where id=57;
+-----------+----------+------------+-----------+----------------------------------+-----------------+-------------+
| username  | password | first_name | last_name | ha1                              | available_tools | permissions |
+-----------+----------+------------+-----------+----------------------------------+-----------------+-------------+
| admintest | admin    |            |           | 0f8b2e317400eb6bbc94b2ac15b5ab34 | all             | all         |
+-----------+----------+------------+-----------+----------------------------------+-----------------+-------------+
1 row in set (0.00 sec)
`


Then i add first_name, last_name and i can change it:

`
MariaDB [opensips]> select username,password,first_name,last_name,ha1,available_tools,permissions from ocp_admin_privileges where id=57;
+-----------+----------+------------+-----------+----------------------------------+-----------------+-------------+
| username  | password | first_name | last_name | ha1                              | available_tools | permissions |
+-----------+----------+------------+-----------+----------------------------------+-----------------+-------------+
| admintest |          | 123        | 123       | 0f8b2e317400eb6bbc94b2ac15b5ab34 | all             | all         |
+-----------+----------+------------+-----------+----------------------------------+-----------------+-------------+
1 row in set (0.00 sec)

MariaDB [opensips]> select username,password,first_name,last_name,ha1,available_tools,permissions from ocp_admin_privileges where id=57;
+-----------+----------+------------+-----------+----------------------------------+-----------------+-------------+
| username  | password | first_name | last_name | ha1                              | available_tools | permissions |
+-----------+----------+------------+-----------+----------------------------------+-----------------+-------------+
| admintest |          | 123        | 123       | bb7ec84b6becb6edf9ac2c7ef16a04e9 | all             | all         |
+-----------+----------+------------+-----------+----------------------------------+-----------------+-------------+
`

**Comment by khorsmann** [comment]
Could be also an issue with the webinterface itself, i dont go so deep and try to debug the php stuff.
Its running on a CentOS 7.3 64bit maschine.

**Comment by bogdan-iancu** [comment]
I just checked and the problem seems to be in the "edit" admin form - the first and last name are mandatory.
So, when trying to change the pwd for the original admin (added by the query), you will HAVE to set the first and last name.
I will merge in your fix, thank you

**Comment by bogdan-iancu** [comment]
@khorsmann, I merged the fix  (see 92883b4 ) and also did the backports. I will shortly update the online docs too.
Thank you !

**Pull request closed without merging**
