### PR TITLE
Support SIP parameters in dispatcher destination

### PR DESCRIPTION
**Pull request by AustinLangston**

### CODE REVIEW

**Review by vladpaiu — CHANGES_REQUESTED** [review]
Hey Austin,

I'd allow any transport= potential value here, since we might also have ws, wss or who knows what other protocols might come in the future :)

**Comment by bogdan-iancu** [comment]
Or maybe should we allow any kind of URI params, not only transport?

**Comment by AustinLangston** [comment]
@vladpaiu, I modified it here to support any combination of parameters

**Review by vladpaiu — APPROVED** [review]

**Comment by bogdan-iancu** [comment]
just for the records, see 14a8406c623993d6b924eb5a416b39972475e0bb

**Pull request merged**
